---
Coding station
---

### Let's make a datasheet with your name, session, and sampling method
```{r}
require(ggplot2)
wise <- data.frame(name=rep(NA, 25), session=rep(NA, 25), sampling=rep(NA, 25))

### Enter your name using:
### wise$name[ROWNUMBER] <- "Freya"
### press COMMAND + ENTER to run

wise$name[1] <- "Freya"

### Enter your session using:
### wise$session[ROWNUMBER] <- "Morning" or "Afternoon"
### press COMMAND + ENTER to run

wise$session[1] <- "Morning"

### Enter your sampling method using:
### wise$sampling[ROWNUMBER] <- "Angling", "Trawling", "Seining"
### press COMMAND + ENTER to run

wise$sampling[1] <- "Angling"
```

### Check out a plot of fish lengths
```{r}
wisefish <- read.csv("./wisefish.csv")

depth.size <- ggplot() + geom_point(data=wisefish, aes(depth, size), colour="black", fill="red") + theme_classic()
print(depth.size)

### change the colour of the points using colour="COLOUR" (blue, green, yellow, violet, grey, orange, etc!)
depth.size <- ggplot() + geom_point(data=wisefish, aes(depth, size), colour="red") + theme_classic()
print(depth.size)

### change the shape of the points using shape="NUMBER" (see chart for shape numbers).
depth.size <- ggplot() + geom_point(data=wisefish, aes(depth, size), col="red", shape=1) + theme_classic()
print(depth.size)

### change the size of the points using size="NUMBER" (bigger number = bigger point).
depth.size <- ggplot() + geom_point(data=wisefish, aes(depth, size), col="red", shape=1, size=3) + theme_classic()
print(depth.size)

```

### How many fish were collected in this study?
```{r}
### Counting the points will take WAY too long! Let's save time by coding!
### Our dataset is called "wisefish". Each row represents one fish, so we will automatically count the rows using the nrow() function on the dataset "wisefish"

nrow(wisefish)

```



